[project]
name = "topt-proto"
version = "0.1.0"
description = "Python prototype of circuit rewrites related to T gate optimisation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytket>=1.37.0",
    "pytket-qiskit>=0.62.0",
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]
